#topic config
kafka-retry:
  topic-base-name: dados-lgpd
  group-id: aws-consumer
  max-retries: 3
  topic-retry-prefix: ${kafka-retry.topic-base-name}-${kafka-retry.group-id}
  consumers:
    - id: main
      delay: 0
      topics:
        - topic-name: ${kafka-retry.topic-base-name}
          retry-value: 0
    - id: first-retry
      delay: 1000
      topics:
        - topic-name: ${kafka-retry.topic-retry-prefix}-first-retry
          retry-value: 1
    - id: second-retry
      delay: 2000
      topics:
        - topic-name: ${kafka-retry.topic-retry-prefix}-second-retry
          retry-value: 2
    - id: third-retry
      delay: 4000
      topics:
        - topic-name: ${kafka-retry.topic-retry-prefix}-third-retry
          retry-value: 3
    - id: dlt
      delay: 6000
      topics:
        - topic-name: ${kafka-retry.topic-retry-prefix}-dlt
          retry-value: 4
  exceptions:
    recoverable:
      - com.kafka.retry.exceptions.RecoverableException
    unrecoverable:

spring:
  kafka:
    consumer:
      group-id: aws-consumer
      options.enable.auto.commit: false
      bootstrap-servers: http://localhost:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kafka.retry.serializers.MessageDTODeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kafka.retry.serializers.MessageDTOSerializer
